accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns =[ 
    path('',views.welcome, name="welcome"),
    path('login/',views.login_user, name="login"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout', views.logout_user, name="logout"),
    ]
    
    

books/urls.py
from django.urls import path
from . import views
app_name = 'books'

#These are the different urls for our "books" app. They contain what they'll show on a user's http request,
# the name of the view function or class that calls/responds to them as well as their names.

urlpatterns = [
    path("",views.book_overview,name="book_overview"),
    path("<int:pk>/",views.book_detail,name="book_detail"),
    path("<int:pk>/borrow/", views.borrow, name="borrow"),
    path("activity", views.activity, name="activity"),
    path("urlmessage", views.urlmessage, name="message"),
    path('search_book/', views.BookSearchView.as_view(), name= 'search_book'),
    ]

library_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('books/', include('books.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

library_project/templates/activity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "main.html" %}
    {% load static %}
    {% block page_content %}
    <br><br>
    <center class="content-border">
        <h1>your activity</h1>
        <br><br>
        <p>{% if messages %}
            {% for message in messages %}
             {{message}}
            {% endfor %}
           {% endif %}
        <table class="table-content">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Email address</th>
                    <th>Title</th>
                    <th>Borrow Date</th>
                    <th>Return date</th>
                    <th>Days Remaining</th>
                    <th>Fine</th>
                </tr>
            </thead>
            <tbody>
                {% for aform in laforms %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ aform.email_address }}</td>
                    <td>{{ aform.book_title }}</td>
                    <td>{{ aform.borrow_date }}</td>
                    <td>{{ aform.return_date }}</td>
                    <td>{{ aform.days_remaining }}</td>
                    <td>{{ aform.Fine }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
       
    </center>
    {% endblock %}
</body>
</html>

library_project/templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends "main.html" %}
    {% load static %}
    
</head>
<body>
    {% block page_content %}
    <br>
    <br>
    <p style="color:wheat;" class="pbook_detail">{{ detail.title }} was published on {{ detail.publication_date }} and is {{ detail.status }}</p> 
    <p><p style="color:wheat;" class="pbook_detail">Book_ID: {{ detail.pk }} </p>
    <div class="rowbook_detail">
        <div>
            <img class="imgbook_detail" src="{{detail.cover_photo.url}}" alt="">
        </div>
        
        <div class="contentbook_detail">
            <h5>Subject</h5>
            <p>{{ detail.subject_area }}</p>
            <h5>Book details</h5>
            <p>{{detail.description}}</p>
            <h5>Author</h5>
            <p>{{detail.author}}</p>
            <br>
            <a class="borrowlink" href="{% url 'books:borrow' detail.pk  %}">Borrow</a>
        </div>
    </div>
    <p>{% if messages %}
        {% for message in messages %}
         {{message}}
        {% endfor %}
       {% endif %}
    {% endblock %}
</body>
</html>

library_project/templates/book_overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends "main.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body>
    {% block page_content %}
    <br>
    <br>
    <div class="flex-row">
        {% for book in books %}
        <div class="cardshape">
            <img class="overviewimg"  src="{{book.cover_photo.url}}" alt= "bookcover">
                {% if book.status == 'Available' %}
                <p style="background:green;font-size: 15px;height:16px;width:fit-content;border-radius: 50px;margin-top: -3px;text-align: center;">{{ book.status }}</p>
                {% else %}
                <p style="background:grey;font-size: 15px;height:16px;width:fit-content;border-radius: 50px;margin-top: -3px;text-align: center;">{{ book.status }}</p>
                {% endif %}
                <h5><strong>{{ book.title }}</strong></h5>
                <p>Subject: {{ book.subject_area }}</p>
                <div class="aboutlinkdiv"><a class="aboutlink" href= "{% url 'books:book_detail' book.pk %}">About</a></div>
        </div>     
        {% endfor %}      
    </div>
    {% endblock %}
    <div class="body"></div>
</body>
</html>

library_project/templates/borrow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "main.html" %}
    {% load static %}
    {% block page_content %}
    <br><br>
    <center>
        <div class="content-border">
            <h1>Confirm your details below to secure the book</h1>
            <p>
                {% if messages %}
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                {% endif %}
            </p>
        </div>
        <br><br>
        <form method= POST class="login">
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Submit" class="form-button">
        </form>
    </center>
    {% endblock %}
</body>
</html>

library_project/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
    {% extends 'regbase.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'regbase.css' %}">
</head>
<body>
    {% block page_content %}
        <br><br>
        <center>
            <div class="content-border">
                <h1>Welcome Dear Student</h1>
                <h2>LogIn Below</h3>
                <br><br>
                <p> 
                {% if messages %}
                {% for message in messages %}
                {{message}}
                {% endfor %}
                {% endif %}
                </p>
            </div>
            
            <div class="login">
                <br><br>
                <form method= POST>
                    {% csrf_token %}
                    <input type="text" name="username" class="form-input" placeholder="Input your Username here">
                    <br>
                    <input type="password" name="password" class="form-input" placeholder="Input your Password here">
                    <br>
                    <input type="submit" value="Login" class="form-button">

                    <p>Don't have an account?<a href="{% url 'accounts:signup' %}">Register</a> </p>
                </form>
            </div>
        </center>
    {% endblock %}
</body>
</html>

library_project/templates/main.html
<!DOCTYPE html>
<html lang="en" style="background-image: url('/static/background/web-body.jpg');background-repeat: no-repeat;background-size:cover;background-position: center;
height:100%;">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Document
        {% block title %}
        {% endblock%}
    </title>
</head>
<body>
    <nav class="navbar">
        <a class="maina" font-size="60px" href="{% url 'books:book_overview' %}">Bookshelf</a>
        <a class="maina"  font-size="60px" href="{% url 'books:activity' %}">Activity</a>
        {% if user.is_authenticated %}
        <a class="maina" font-size="60px" href="{% url 'logout' %}">LogOut</a>
        {% else %}
        <a class="maina" font-size="60px" href="{% url 'accounts:login' %}">Login</a>
        {% endif%}
        <a class="maina" font-size="60px" href=""></a>
        <p>Welcome,{{user.username}}</p>
        <form class="maina" action="{% url 'books:search_book' %}" method="get">
            {% csrf_token %}
            <input style="height:30px;width:400px;border-radius:30px;font-size:20px;border-width:2px;border-color: white;margin-top:-5px; " type="text" placeholder="Search Book" name="q" aria-label="Search" value="{{ request.GET.q }}">
            <button style="height:30px;border-radius:20px;font-size:20px;border-width:1px;border-color: black;margin-top:-5px; " type="submit">Search</button>
        </form>
    </nav>
    <div>
        {% block page_content %}
        {% endblock %}
    </div>
</body>
</html>

library_project/templates/regbase.html
<!DOCTYPE html>
<html lang="en" style="background-image: url('/static/background/login.jpg');background-repeat: no-repeat;background-size:cover;background-position: center;
height:100%;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'regbase.css' %}">
    <title>Document
    {% block title %}
    {% endblock%}
    </title>
</head>
<body>
    <div>
        {% block page_content %}
        {% endblock%}
    </div>
</body>
</html>

library_project/templates/search_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends "main.html" %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body>
    {% block page_content %}
    <br>
    <br>
    <div class="flex-row">
        {% for book in object_list %}
        <div class="cardshape">
            <img class="overviewimg"  src="{{book.cover_photo.url}}" alt= "bookcover">
            {% if book.status == 'Available' %}
            <p style="background:green;font-size: 15px;height:16px;width:fit-content;border-radius: 50px;margin-top: -3px;text-align: center;">{{ book.status }}</p>
            {% else %}
            <p style="background:grey;font-size: 15px;height:16px;width:fit-content;border-radius: 50px;margin-top: -3px;text-align: center;padding:0%;">{{ book.status }}</p>
            {% endif %}
            <h5><strong>{{ book.title }}</strong></h5>
            <p>Subject: {{ book.subject_area }}</p>
            <div class="aboutlinkdiv"><a class="aboutlink" href= "{% url 'books:book_detail' book.pk %}">About</a></div>
        </div>     
        {% endfor %}      
    </div>
    {% endblock %}
    <div class="body"></div>
</body>
</html>

library_project/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Document 
    </title>
    {% extends "regbase.html" %}
    {% load static %}
</head>
<body>
    {% block page_content %}
        <center>
            <h2 align="center" class="content-borders">Registration Form</h2>
            <form method="POST" class="registerform">
                {% csrf_token %}
                {{form.as_p}}
                <p>Already have an account |<a href="#">SignIn Here</a></p>
                <button type="submit" class="form-button">sign up</button>
            </form>
        </center>
    {% endblock %}
</body>
</html>

library_project/templates/urlmessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{% if messages %}
        {% for message in messages %}
         {{message}}
        {% endfor %}
       {% endif %}
</body>
</html>

library_project/templates/welcome.html
<!DOCTYPE html>
<html lang="en" style="background-image: url('/static/background/welcome.jpg');
background-repeat: no-repeat;background-size:cover;background-position: center;
height:100%;">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link  rel="stylesheet" href="{% static 'welcome.css' %}">
</head>
{% block page_content %}

<body class="text">
    <center>
        <h1>Welcome to GroupMSample Library</h1>

    <p>your are a.....</p>
    <div class="main-wlcm">
        <div class="ind-wlcm"> <img class="img-icon" src="/static/background/librarian.jpg" alt="librarianimg"> <a href="{% url 'admin:index' %}">Librarian</a> </div>
        <br>
        <div class="ind-wlcm"> <img class="img-icon" src="/static/background/student.jpg" alt="librarianimg"> <a href="{% url 'accounts:login' %}">Student</a> </div>
    </div>
  

    </center>
</body>
{% endblock %}
</html>